version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false
  go: '1.24'

linters:
  enable:
    - errcheck
    - govet
    - staticcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0